# Generated by Django 5.1.1 on 2024-09-18 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=50)),
                ('crop_type', models.CharField(max_length=50)),
                ('growing_season', models.CharField(max_length=50)),
                ('ideal_temperature_min', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ideal_temperature_max', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ideal_humidity_min', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ideal_humidity_max', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ideal_rainfall_min', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ideal_rainfall_max', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('preferred_soil_texture', models.CharField(choices=[('Sandy', 'Sandy'), ('Loamy', 'Loamy'), ('Clay', 'Clay'), ('Silty', 'Silty'), ('Peaty', 'Peaty'), ('Chalky', 'Chalky'), ('Any', 'Any')], default='Any', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('total_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('Farmer', 'Farmer'), ('Expert', 'Expert')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('recommendation_text', models.TextField()),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm_management.crop')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm_management.farm')),
            ],
        ),
        migrations.CreateModel(
            name='Soil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph_level', models.DecimalField(decimal_places=2, max_digits=4)),
                ('nitrogen_level', models.DecimalField(decimal_places=2, max_digits=5)),
                ('phosphorus_level', models.DecimalField(decimal_places=2, max_digits=5)),
                ('potassium_level', models.DecimalField(decimal_places=2, max_digits=5)),
                ('texture', models.CharField(choices=[('Sandy', 'Sandy'), ('Loamy', 'Loamy'), ('Clay', 'Clay'), ('Silty', 'Silty'), ('Peaty', 'Peaty'), ('Chalky', 'Chalky')], default='Loamy', max_length=50)),
                ('farm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='farm_management.farm')),
            ],
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rainfall', models.DecimalField(decimal_places=2, max_digits=5)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm_management.farm')),
            ],
        ),
    ]
