# Generated by Django 5.1.1 on 2024-09-29 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("farm_management", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CropRotation",
        ),
    ]
