# Generated by Django 5.1.1 on 2024-09-16 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0002_farm_latitude_farm_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='ideal_humidity_max',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='crop',
            name='ideal_humidity_min',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='crop',
            name='ideal_rainfall_max',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='crop',
            name='ideal_rainfall_min',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='crop',
            name='ideal_temperature_max',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='crop',
            name='ideal_temperature_min',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='farm',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.CreateModel(
            name='Soil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph_level', models.DecimalField(decimal_places=2, max_digits=4)),
                ('nitrogen_level', models.DecimalField(decimal_places=2, max_digits=5)),
                ('phosphorus_level', models.DecimalField(decimal_places=2, max_digits=5)),
                ('potassium_level', models.DecimalField(decimal_places=2, max_digits=5)),
                ('farm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='farm_management.farm')),
            ],
        ),
    ]
