# Generated by Django 5.1.1 on 2024-09-20 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0002_alter_farm_options_rename_user_farm_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdata',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_data', to='farm_management.farm'),
        ),
    ]
