# Generated by Django 5.1.1 on 2024-09-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farm_management", "0002_delete_croprotation"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cropyieldprediction",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="cropyieldprediction",
            name="crop",
        ),
        migrations.RemoveField(
            model_name="cropyieldprediction",
            name="farm",
        ),
        migrations.AddField(
            model_name="farm",
            name="crops",
            field=models.ManyToManyField(
                blank=True, related_name="farms", to="farm_management.crop"
            ),
        ),
        migrations.DeleteModel(
            name="CropRotationPrediction",
        ),
        migrations.DeleteModel(
            name="CropYieldPrediction",
        ),
    ]
