# Generated by Django 5.1.1 on 2024-09-21 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0004_alter_farm_options_alter_farm_owner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farm',
            old_name='owner',
            new_name='user',
        ),
    ]
