# Generated by Django 5.1.1 on 2024-09-25 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farm_management", "0005_rename_owner_farm_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="weatherdata",
            name="cloudiness",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="feels_like",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="grnd_level",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="pressure",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="sea_level",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="temp_max",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="temp_min",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="visibility",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="wind_direction",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="wind_gust",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="wind_speed",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="humidity",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="rainfall",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="temperature",
            field=models.FloatField(default=0),
        ),
    ]
