# Generated by Django 5.1.1 on 2024-09-26 06:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "farm_management",
            "0006_weatherdata_cloudiness_weatherdata_feels_like_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="farm",
            name="total_area",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="user_type",
        ),
        migrations.RemoveField(
            model_name="weatherdata",
            name="cloudiness",
        ),
        migrations.RemoveField(
            model_name="weatherdata",
            name="feels_like",
        ),
        migrations.RemoveField(
            model_name="weatherdata",
            name="grnd_level",
        ),
        migrations.RemoveField(
            model_name="weatherdata",
            name="pressure",
        ),
        migrations.RemoveField(
            model_name="weatherdata",
            name="sea_level",
        ),
        migrations.RemoveField(
            model_name="weatherdata",
            name="temp_max",
        ),
        migrations.RemoveField(
            model_name="weatherdata",
            name="temp_min",
        ),
        migrations.RemoveField(
            model_name="weatherdata",
            name="visibility",
        ),
        migrations.RemoveField(
            model_name="weatherdata",
            name="wind_direction",
        ),
        migrations.RemoveField(
            model_name="weatherdata",
            name="wind_gust",
        ),
        migrations.RemoveField(
            model_name="weatherdata",
            name="wind_speed",
        ),
        migrations.AlterField(
            model_name="farm",
            name="farm_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="farm",
            name="latitude",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="farm",
            name="location",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="farm",
            name="longitude",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="humidity",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="rainfall",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="temperature",
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="farm_management.farm",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CropIdealConditions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ideal_temperature_min", models.FloatField()),
                ("ideal_temperature_max", models.FloatField()),
                ("ideal_rainfall_min", models.FloatField()),
                ("ideal_rainfall_max", models.FloatField()),
                ("ideal_humidity_min", models.FloatField()),
                ("ideal_humidity_max", models.FloatField()),
                (
                    "crop",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ideal_conditions",
                        to="farm_management.crop",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CropRotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="farm_management.crop",
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crop_rotations",
                        to="farm_management.farm",
                    ),
                ),
            ],
            options={
                "ordering": ["-year"],
                "unique_together": {("farm", "year")},
            },
        ),
        migrations.CreateModel(
            name="CropRotationPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("confidence", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crop_rotation_predictions",
                        to="farm_management.farm",
                    ),
                ),
                (
                    "predicted_crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="farm_management.crop",
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-created_at"],
                "unique_together": {("farm", "year")},
            },
        ),
        migrations.CreateModel(
            name="CropYieldPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("predicted_yield", models.FloatField()),
                ("confidence", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="farm_management.crop",
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crop_yield_predictions",
                        to="farm_management.farm",
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-created_at"],
                "unique_together": {("farm", "crop", "year")},
            },
        ),
        migrations.CreateModel(
            name="WeatherForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("temperature_max", models.FloatField()),
                ("temperature_min", models.FloatField()),
                ("rainfall", models.FloatField()),
                ("humidity", models.FloatField()),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weather_forecasts",
                        to="farm_management.farm",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
                "unique_together": {("farm", "date")},
            },
        ),
        migrations.CreateModel(
            name="WeatherImpact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("impact_description", models.TextField()),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="farm_management.crop",
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weather_impacts",
                        to="farm_management.farm",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
                "unique_together": {("farm", "crop", "date")},
            },
        ),
    ]
