# Generated by Django 5.1.1 on 2024-09-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "farm_management",
            "0007_remove_farm_total_area_remove_profile_user_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="weatherdata",
            options={},
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="cloudiness",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="feels_like",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="pressure",
            field=models.IntegerField(default=1013),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="temp_max",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="temp_min",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="visibility",
            field=models.IntegerField(default=10000),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="weather_description",
            field=models.CharField(default="Clear sky", max_length=200),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="weather_icon",
            field=models.CharField(default="01d", max_length=10),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="weather_main",
            field=models.CharField(default="Clear", max_length=100),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="wind_direction",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="wind_gust",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="wind_speed",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="humidity",
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="rainfall",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="temperature",
            field=models.FloatField(default=0.0),
        ),
    ]
